#!/bin/zsh

GOTARBALL=go1.3.src.tar.gz
GOURL=http://golang.org/dl/${GOTARBALL}
GODIR=/custom/golang
mkdir -p $GODIR

TMPGO=$(mktemp -d)
cd $TMPGO && curl -L -s -O $GOURL
tar xvzf $GOTARBALL -C $GODIR && cd $GODIR/go/src
./all.bash

# Additional tool
yum -y install mercurial
