#!/bin/bash

#Install latest vim and include python support if present
CUSTOMDIR=/custom
VIMDIR=${CUSTOMDIR}/dotfiles/vim
VIMVERSION=vim-7.4
VIMURL=ftp://ftp.vim.org/pub/vim/unix/${VIMVERSION}.tar.bz2
TMPVIM=$(mktemp -d)
cd $TMPVIM && curl -s -O $VIMURL
tar xvjf ${VIMVERSION}.tar.bz2 && cd ${VIMVERSION}

#Check for python installation
PYFULL=3.3.2
PYMAJOR=3.3
PYCONFIG=/custom/pyenv/versions/${PYFULL}/lib/python${PYMAJOR}/config-${PYMAJOR}

if [ -d ${PYCONFIG} ]; then
    pyenv global ${PYFULL}
    LDFLAGS='-export-dynamic' ./configure --enable-python3interp --enable-multibyte \
        --with-features=huge --with-python3-config-dir=${PYCONFIG} --enable-gui=no \
        --with-x=yes
else
    ./configure --with-features=huge --enable-multibyte --enable-gui=no
fi

make -j6
cp src/vim ${CUSTOMDIR}/bin/
cp -R runtime $VIMDIR/
