#!/bin/zsh

CUSTOMDIR=/custom

install_go14 () {
    TMPGO4=$(mktemp -d)
    GO4TARBALL=go1.4.2.linux-amd64.tar.gz
    GO4DIR=/root/go1.4
    mkdir -p $GO4DIR
    cd $TMPGO4 && curl -L -s -O https://storage.googleapis.com/golang/${GO4TARBALL}
    tar xvzf $GO4TARBALL
    mv $TMPGO4/go/* $GO4DIR/

}

install_go () {
    GOTARBALL=go1.6.2.src.tar.gz
    GOURL=https://storage.googleapis.com/golang/${GOTARBALL}
    GODIR=${CUSTOMDIR}/golang
    mkdir -p $GODIR

    TMPGO=$(mktemp -d)
    cd $TMPGO && curl -L -s -O $GOURL
    tar xvzf $GOTARBALL -C $GODIR && cd $GODIR/go/src
    ./all.bash
}


install_packages () {
# Additional tool
    yum -y install mercurial rpm-build ruby-devel gcc-c++ glibc-static libstdc++-static
    gem install fpm --no-ri --no-rdoc
}


do_vim_setup () {
# setup vim configurations
    GOMODDIR=${CUSTOMDIR}/stevedore/modules/go
    VIMDIR=${CUSTOMDIR}/dotfiles/vim

    if [ -e ${VIMDIR} ]; then
        if [ -e "${GOMODDIR}/.vimrc.before.local" ]; then
            cp ${GOMODDIR}/.vimrc.before.local ${VIMDIR}/
        fi
        if [ -e "${GOMODDIR}/.vimrc.local" ]; then
            cp ${GOMODDIR}/.vimrc.local ${VIMDIR}/
        fi
        if [ -e "${GOMODDIR}/.vimrc.bundles.local" ]; then
            cp ${GOMODDIR}/.vimrc.local ${VIMDIR}/
        fi

        ${CUSTOMDIR}/bin/vim -e -s -u ${VIMDIR}/.vimrc +PluginInstall +qall
        echo Done installing bundle
    fi
}

install_zmq () {
    ZMQTARBALL=zeromq-4.0.4.tar.gz
    ZMQURL=http://download.zeromq.org/${ZMQTARBALL}
    TMPZMQ=$(mktemp -d)
    cd $TMPZMQ && curl -L -s -O $ZMQURL
    tar xvzf $ZMQTARBALL && cd zeromq-4.0.4 
    ./configure && make -j7 && make install
    echo "/usr/local/lib" > /etc/ld.so.conf.d/zmq.conf
    ldconfig
}

main () {
    install_go14
    install_go
    #install_packages
    do_vim_setup
    #install_zmq
}

main
