#!/bin/zsh

GOTARBALL=go1.3.src.tar.gz
GOURL=http://golang.org/dl/${GOTARBALL}
GODIR=${CUSTOMDIR}/golang
mkdir -p $GODIR

TMPGO=$(mktemp -d)
cd $TMPGO && curl -L -s -O $GOURL
tar xvzf $GOTARBALL -C $GODIR && cd $GODIR/go/src
./all.bash

# Additional tool
yum -y install mercurial rpm-build ruby-devel
gem install fpm --no-ri --no-rdoc

# setup vim configurations
GODIR=${CUSTOMDIR}/stevedore/modules/go
VIMDIR=${CUSTOMDIR}/dotfiles/vim

if [ -e ${VIMDIR} ]; then
    if [ -e "${GODIR}/.vimrc.before.local" ]; then
        cp ${GODIR}/.vimrc.before.local ${VIMDIR}/
    fi
    if [ -e "${GODIR}/.vimrc.local" ]; then
        cp ${GODIR}/.vimrc.local ${VIMDIR}/
    fi
    if [ -e "${GODIR}/.vimrc.bundles.local" ]; then
        cp ${GODIR}/.vimrc.local ${VIMDIR}/
    fi
fi
