#!/bin/zsh
CUSTOMDIR=/custom
VIMDIR=${CUSTOMDIR}/dotfiles/vim
VIMBUNDLE=${VIMDIR}/bundle

install_js_modules () {
    #yum makecache fast
    #yum -y install cmake gcc-c++ nodejs npm ruby --enablerepo=epel
    #npm install -g yo gulp bower generator-generator generator-angular generator-gulp-angular 
    #npm install -g webpack webpack-dev-server
    #gem install sass
    apk add nodejs
}

install_js_vim_config () {
    JSDIR=${CUSTOMDIR}/stevedore/modules/js
    if [ -e ${VIMDIR} ]; then
        if [ -e "${JSDIR}/.vimrc.before.local" ]; then
            cp ${JSDIR}/.vimrc.before.local ${VIMDIR}/
        fi
        if [ -e "${JSDIR}/.vimrc.local" ]; then
            cp ${JSDIR}/.vimrc.local ${VIMDIR}/
        fi
        if [ -e "${JSDIR}/.vimrc.bundles.local" ]; then
            cp ${JSDIR}/.vimrc.bundles.local ${VIMDIR}/
        fi
fi

}

install_bundle () {
    echo installing bundle
    /usr/bin/vim -e -s -u ${VIMDIR}/.vimrc +PluginInstall +qall
    echo Done installing bundle
}


install_youcomplete_me () {
    if [ -e ${VIMBUNDLE}/YouCompleteMe ]; then
        echo installing youcompleteme
        cd ${VIMBUNDLE}/YouCompleteMe
        ./install.sh
    fi

}

main () {
    install_js_modules
    install_js_vim_config
    install_bundle
    install_youcomplete_me
}

main
