#!/bin/zsh
CUSTOMDIR=/custom
VIMDIR=${CUSTOMDIR}/dotfiles/vim
VIMBUNDLE=${VIMDIR}/bundle

install_js_modules () {
    yum makecache fast
    yum -y install cmake gcc-c++ pcre-devel --enablerepo=epel
    curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
    yum -y install nodejs
    npm install -g create-react-app@1.3.3 
}

install_editorconfig_core(){
    cd $(mktemp -d)
    curl -O -L https://github.com/editorconfig/editorconfig-core-c/archive/v0.12.1.tar.gz
    tar xvzf v0.12.1.tar.gz
    cd editorconfig-core-c-0.12.1/
    cmake .
    make install
}

install_js_vim_config () {
    JSDIR=${CUSTOMDIR}/stevedore/modules/js
    if [ -e ${VIMDIR} ]; then
        if [ -e "${JSDIR}/.vimrc.before.local" ]; then
            cp ${JSDIR}/.vimrc.before.local ${VIMDIR}/
        fi
        if [ -e "${JSDIR}/.vimrc.local" ]; then
            cp ${JSDIR}/.vimrc.local ${VIMDIR}/
        fi
        if [ -e "${JSDIR}/.vimrc.bundles.local" ]; then
            cp ${JSDIR}/.vimrc.bundles.local ${VIMDIR}/
        fi
fi

}

install_bundle () {
    echo installing bundle
    $CUSTOMDIR/bin/vim -e -s -u ${VIMDIR}/.vimrc +PluginInstall +qall
    echo Done installing bundle
}


install_youcomplete_me () {
    if [ -e ${VIMBUNDLE}/YouCompleteMe ]; then
        echo installing youcompleteme
        cd ${VIMBUNDLE}/YouCompleteMe
        ./install.sh
    fi

}

main () {
    install_js_modules
    install_editorconfig_core
    install_js_vim_config
    install_bundle
    install_youcomplete_me
}

main
