#!/bin/zsh

CUSTOMDIR=/custom
PYENV_ROOT=${CUSTOMDIR}/pyenv

## - install pyenv(+virtualenv)
yum -y install zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel
git clone git://github.com/yyuu/pyenv.git $PYENV_ROOT
ln -s /proc/self/fd /dev/fd
git clone git://github.com/yyuu/pyenv-virtualenv.git ${PYENV_ROOT}/plugins/pyenv-virtualenv

## - activate pyenv
if [ -d "${PYENV_ROOT}/bin" ] 
then 
    export PYENV_ROOT
    export PATH="${PYENV_ROOT}/bin:$PATH"
    eval "$(pyenv init -)"
    pyenv rehash
fi

## - install python and friends
pyenv install 3.3.4 2.7.6
pyenv global 3.3.4
pip install virtualenv jedi 
LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 pip install pytz rackspace-novaclient


