#!/bin/zsh

#Install latest vim and include python support if present
CUSTOMDIR=/custom
VIMDIR=${CUSTOMDIR}/dotfiles/vim
VIMVERSION=vim-7.4
VIMURL=ftp://ftp.vim.org/pub/vim/unix/${VIMVERSION}.tar.bz2
TMPVIM=$(mktemp -d)
cd $TMPVIM && curl -s -O $VIMURL
tar xvjf ${VIMVERSION}.tar.bz2 && cd vim74

#LDFLAGS='-export-dynamic' ./configure --enable-pythoninterp --enable-multibyte \
./configure --enable-pythoninterp --enable-multibyte \
    --with-python-config-dir=/usr/lib64/python2.7/config \
    --with-features=huge --enable-gui=no \
    --with-x=yes --enable-luainterp=yes  --with-lua-prefix=/usr

make -j6
cp src/vim ${CUSTOMDIR}/bin/
cp -R runtime $VIMDIR/
rm -rf $TMPVIM

# setup for powerfile fonts
curl -L -o /usr/share/fonts/powerlinesymbols.otf https://github.com/Lokaltog/powerline/blob/develop/font/PowerlineSymbols.otf\?raw\=true
curl -o /usr/share/fonts/Inconsolata-powerline.otf https://raw2.github.com/Lokaltog/powerline-fonts/master/Inconsolata/Inconsolata%20for%20Powerline.otf
curl -o /usr/share/fontconfig/conf.avail/10-powerline-symbols.conf https://raw2.github.com/Lokaltog/powerline/develop/font/10-powerline-symbols.conf
cd /etc/fonts/conf.d && ln -sf /usr/share/fontconfig/conf.avail/10-powerline-symbols.conf .
fc-cache -vf /usr/share/fonts


