#!/bin/zsh

#Install latest vim and include python support if present
CUSTOMDIR=/custom
VIMDIR=${CUSTOMDIR}/dotfiles/vim
VIMVERSION=vim-7.4
VIMURL=ftp://ftp.vim.org/pub/vim/unix/${VIMVERSION}.tar.bz2
TMPVIM=$(mktemp -d)
cd $TMPVIM && curl -s -O $VIMURL
tar xvjf ${VIMVERSION}.tar.bz2 && cd vim74

Check for python installation
PYFULL=2.7.6
PYMAJOR=2.7
PYCONFIG=/custom/pyenv/versions/${PYFULL}/lib/python${PYMAJOR}/config

if [ -d ${PYCONFIG} ]; then
    pyenv global ${PYFULL}
    export PATH=${CUSTOMDIR}/pyenv/bin:${CUSTOMDIR}/pyenv/shims:${PATH}
    LDFLAGS='-export-dynamic' ./configure --enable-pythoninterp --enable-multibyte \
        --with-features=huge --with-python-config-dir=${PYCONFIG} --enable-gui=no \
        --with-x=yes --enable-luainterp=yes  --with-lua-prefix=/usr
else
    ./configure --with-features=huge --enable-multibyte --enable-gui=no \
                --enable-luainterp=yes  --with-lua-prefix=/usr
fi

make -j6
cp src/vim ${CUSTOMDIR}/bin/
cp -R runtime $VIMDIR/
rm -rf $TMPVIM

# setup for powerfile fonts
curl -L -o /usr/share/fonts/powerlinesymbols.otf https://github.com/Lokaltog/powerline/blob/develop/font/PowerlineSymbols.otf\?raw\=true
curl -o /usr/share/fonts/Inconsolata-powerline.otf https://raw2.github.com/Lokaltog/powerline-fonts/master/Inconsolata/Inconsolata%20for%20Powerline.otf
curl -o /usr/share/fontconfig/conf.avail/10-powerline-symbols.conf https://raw2.github.com/Lokaltog/powerline/develop/font/10-powerline-symbols.conf
cd /etc/fonts/conf.d && ln -sf /usr/share/fontconfig/conf.avail/10-powerline-symbols.conf .
fc-cache -vf /usr/share/fonts


# setup vim configurations for python2
PYDIR=${CUSTOMDIR}/stevedore/modules/python2

if [ -e ${VIMDIR} ]; then
    if [ -e "${PYDIR}/.vimrc.before.local" ]; then
        cp ${PYDIR}/.vimrc.before.local ${VIMDIR}/
    fi
    if [ -e "${PYDIR}/.vimrc.local" ]; then
        cp ${PYDIR}/.vimrc.local ${VIMDIR}/
    fi
fi
