#!/bin/zsh

#Install latest vim and include python support if present
CUSTOMDIR=/custom
VIMDIR=${CUSTOMDIR}/dotfiles/vim
VIMVERSION=vim-7.4

install_vim () {
    PYFULL=2.7.6
    PYMAJOR=2.7
    PYCONFIG=/custom/pyenv/versions/${PYFULL}/lib/python${PYMAJOR}/config

    VIMURL=ftp://ftp.vim.org/pub/vim/unix/${VIMVERSION}.tar.bz2
    TMPVIM=$(mktemp -d)
    cd $TMPVIM && curl -s -O $VIMURL
    tar xvjf ${VIMVERSION}.tar.bz2 && cd vim74

    if [ -d ${PYCONFIG} ]; then
        pyenv global ${PYFULL}
        export PATH=${CUSTOMDIR}/pyenv/bin:${CUSTOMDIR}/pyenv/shims:${PATH}
    #LDFLAGS='-export-dynamic' ./configure --enable-pythoninterp --enable-multibyte \
        ./configure --enable-pythoninterp --enable-multibyte \
            --with-features=huge --with-python-config-dir=${PYCONFIG} --enable-gui=no \
            --with-x=yes --enable-luainterp=yes  --with-lua-prefix=/usr
    fi

    make -j6
    cp src/vim ${CUSTOMDIR}/bin/
    cp -R runtime $VIMDIR/
    rm -rf $TMPVIM
}

install_fonts () {
# setup for powerfile fonts
    curl -L -o /usr/share/fonts/powerlinesymbols.otf https://github.com/Lokaltog/powerline/blob/develop/font/PowerlineSymbols.otf\?raw\=true
    curl -o /usr/share/fonts/Inconsolata-powerline.otf https://raw2.github.com/Lokaltog/powerline-fonts/master/Inconsolata/Inconsolata%20for%20Powerline.otf
    curl -o /usr/share/fontconfig/conf.avail/10-powerline-symbols.conf https://raw2.github.com/Lokaltog/powerline/develop/font/10-powerline-symbols.conf
    cd /etc/fonts/conf.d 
    ln -sf /usr/share/fontconfig/conf.avail/10-powerline-symbols.conf .
    fc-cache -vf /usr/share/fonts
}

install_packages () {
    yum -y install ctags ncurses ncurses-libs ncurses-devel fontconfig lua lua-devel cmake gcc-c++
}

install_vim_config () {
    mkdir -p /custom/bin && mkdir -p /custom/dotfiles/vim 

    curl http://beyondgrep.com/ack-2.10-single-file > /usr/local/bin/ack 
    chmod 0755 /usr/local/bin/ack

    git clone https://github.com/gmarik/Vundle.vim.git /custom/dotfiles/vim/bundle/Vundle.vim
    git clone https://github.com/cybersiddhu/spf13-vim.git -b feature/modular /custom/dotfiles/vim/spf13

    ln -sf /custom/dotfiles/vim/spf13/.vimrc.before /custom/dotfiles/vim/.vimrc.before
    ln -sf /custom/dotfiles/vim/spf13/.vimrc.before.fork /custom/dotfiles/vim/.vimrc.before.fork
    ln -sf /custom/dotfiles/vim/spf13/.vimrc /custom/dotfiles/vim/.vimrc 
    ln -sf /custom/dotfiles/vim/spf13/.vimrc.bundles /custom/dotfiles/vim/.vimrc.bundles
    ln -sf /custom/dotfiles/vim/spf13/.vimrc.bundles.fork /custom/dotfiles/vim/.vimrc.bundles.fork
    ln -sf /custom/dotfiles/vim/spf13/.vimrc.fork /custom/dotfiles/vim/.vimrc.fork
}

main () {
    install_vim_config
    install_packages
    install_vim
    install_fonts
}

main
