#!/bin/zsh
CUSTOMDIR=/custom
VIMDIR=${CUSTOMDIR}/dotfiles/vim
VIMBUNDLE=${VIMDIR}/bundle

install_dep () {
    yum -y install java-1.8.0-openjdk-headless ant wget tree unzip ctags cmake
}

install_eclim () {
    yum -y install xorg-x11-server-Xvfb java-1.8.0-openjdk ant wget tree cmake gcc-c++ unzip
    if [ -e ${CUSTOMDIR} ]; then
        TMPJAVA=$(mktemp -d)
        ECTARBALL=eclipse-java-neon-3-linux-gtk-x86_64.tar.gz
        cd $TMPJAVA
        wget http://ftp.osuosl.org/pub/eclipse/technology/epp/downloads/release/neon/3/${ECTARBALL}
        tar xvzf $ECTARBALL -C $CUSTOMDIR
        git clone git://github.com/ervandew/eclim.git
        cd ${TMPJAVA}/eclim
        ant -Declipse.home=${CUSTOMDIR}/eclipse -Dvim.files=${VIMBUNDLE}/eclim
    fi
}

install_java_vim_config () {
    JAVADIR=${CUSTOMDIR}/stevedore/modules/java
    if [ -e ${VIMDIR} ]; then
        if [ -e "${JAVADIR}/.vimrc.before.local" ]; then
            cp ${JAVADIR}/.vimrc.before.local ${VIMDIR}/
        fi
        if [ -e "${JAVADIR}/.vimrc.local" ]; then
            cp ${JAVADIR}/.vimrc.local ${VIMDIR}/
        fi
        if [ -e "${JAVADIR}/.vimrc.bundles.local" ]; then
            cp ${JAVADIR}/.vimrc.bundles.local ${VIMDIR}/
        fi
fi

}

install_gradle () {
    GRADLE_VERSION=gradle-3.4.1
    cd $(mktemp -d) && curl  -L -O https://services.gradle.com/distributions/${GRADLE_VERSION}-bin.zip
    unzip ${GRADLE_VERSION}-bin.zip -d /opt
}

install_bundle () {
    echo installing bundle
    ${CUSTOMDIR}/bin/vim -e -s -u ${VIMDIR}/.vimrc +PluginInstall +qall
    echo Done installing bundle
}

install_youcomplete_me () {
    if [ -e ${VIMBUNDLE}/YouCompleteMe ]; then
        cd ${VIMBUNDLE}/YouCompleteMe
        ./install.py
    fi

}

main () {
    install_java_vim_config
    install_bundle
    install_dep
    install_gradle
    install_youcomplete_me
}

main
