#!/bin/zsh
CUSTOMDIR=/custom
VIMDIR=${CUSTOMDIR}/dotfiles/vim
VIMBUNDLE=${VIMDIR}/bundle

install_eclim () {
    yum -y install xorg-x11-server-Xvfb java-1.7.0-openjdk ant wget tree
    if [ -e ${CUSTOMDIR} ]; then
        TMPJAVA=$(mktemp -d)
        ECTARBALL=eclipse-standard-luna-R-linux-gtk-x86_64.tar.gz
        cd $TMPJAVA
        wget http://ftp.osuosl.org/pub/eclipse/technology/epp/downloads/release/luna/R/${ECTARBALL}
        tar xvzf $ECTARBALL -C $CUSTOMDIR
        git clone git://github.com/ervandew/eclim.git
        cd ${TMPJAVA}/eclim
        ant -Declipse.home=${CUSTOMDIR}/eclipse -Dvim.files=${VIMBUNDLE}
    fi
}

install_vim_config () {
    JAVADIR=${CUSTOMDIR}/stevedore/modules/java
    if [ -e ${VIMDIR} ]; then
        if [ -e "${JAVADIR}/.vimrc.before.local" ]; then
            cp ${JAVADIR}/.vimrc.before.local ${VIMDIR}/
        fi
        if [ -e "${JAVADIR}/.vimrc.local" ]; then
            cp ${JAVADIR}/.vimrc.local ${VIMDIR}/
        fi
        if [ -e "${JAVADIR}/.vimrc.bundles.local" ]; then
            cp ${JAVADIR}/.vimrc.local ${VIMDIR}/
        fi
fi

}

install_bundle () {
    ${CUSTOMDIR}/bin/vim -e -s -u ${VIMDIR}/.vimrc +PluginInstall +qall
}

main () {
    install_bundle
    install_vim_config 
    install_eclim
}

main
